services:
  # Base de datos
  db:
    image: postgres:17-alpine
    container_name: daka-postgres
    environment:
      POSTGRES_DB: technical-test_db
      POSTGRES_USER: technical-test
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U technical-test -d technical-test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: daka-backend
    ports:
      - "3000:3000"
    environment:
      # IMPORTANTE: Aqu√≠ cambiamos localhost por 'db'
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=technical-test
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=technical-test_db
      - JWT_SECRET=clave_secreta_para_docker
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy

  # Frontend (Vue)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: daka-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Esto permite que entres desde Windows
    command: ["npm", "run", "dev", "--", "--host"] 

volumes:
  postgres_dev_data: